name: scanner # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Scan bluetooth LE devices nearby # 79 char long summary
description: |
  This utility scans for nearby LE devices and send it to the context API so the cms-backend
  detect scan events.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  scanner:
    command: bin/scanner $SNAP/bin/scanner

parts:
  scanner:
    source: https://github.com/newtonlb/scanner-snap.git
    source-tag: master
    # See 'snapcraft plugins'
    plugin: python
    python-version: 'python3'
    python-packages: [termcolor,pybluez,bluepy,xlrd, pyserial]
    stage-packages: [bluetooth,libbluetooth-dev,libglib2.0-dev]
